### ISSUE TITLE
Centering the overlay

### ISSUE THREAD

**Issue by tpronk** [u01ai11/MouseView.js#12]
I build a demo using MouseView in PsychoJS: https://gitlab.pavlovia.org/tpronk/demo_mouseview/

I noticed when using Alpa 0.2, the overlay was shifted a bit to the right, revealing a small stripe of the background at the left. 

I could fix this by adding...
`overlay.style.left = '0px'`

Over here...
https://github.com/u01ai11/MouseView.js/blob/6991d820f24ea7ce22f3958152d15c91cdcafd1e/MouseView.js#L96

**Comment by u01ai11** [comment]
Hi @tpronk thanks again for spotting that. 

This is solved in commit 50f97f60187080609e1b67f0b184a5912b20b8c5 

However, there is still an issue with the blurring of the canvas edge itself I need to resolve, but I'll close this particular issue.
