### ISSUE TITLE
Question about removing aperature

### ISSUE THREAD

**Issue by DamonCharlesRoberts** [u01ai11/MouseView.js#25]
This is a great tool and I am excited to learn and work with it some more.

I was playing with the jsPsych demo you have here in `examples/` and was wondering how I would go about removing the aperture after the last image displayed to the user. I thought mouseview.removeAll() would do it, but it does not appear to do so. 

Essentally what I am trying to think about what I'd do is show a series of images, and then have a page to ask a series of questions about the images afterwards. But I wouldn't want the aperture to be there for that; I'd want it to just look like a standard survey-multi-choice page. 

I am not super familiar with js so I may just be overlooking something.

**Comment by DamonCharlesRoberts** [comment]
I think I figured out the issue. I just nested a timeline within a trial.

**Comment by esdalmaijer** [comment]
Thanks for the compliments, and excellent that you managed to solve it!
